#!/usr/bin/env bash
set -euo pipefail

$ANDROID_HOME/platform-tools/adb devices

echo "Waiting to give phone a chance to connect"
sleep 5

$ANDROID_HOME/platform-tools/adb install -r target/release/gdn-app.apk
