#!/usr/bin/env bash
set -euo pipefail

pnpm install

# https://v2.tauri.app/start/prerequisites/#android
rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
