[package]
name = "gdn"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
directories = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
